unit Unit1;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Xml.xmldom, Xml.XMLIntf, Xml.XMLDoc,
  Vcl.StdCtrls, Vcl.ExtCtrls;

type
  TForm1 = class(TForm)
    Memo1: TMemo;
    XMLDocument1: TXMLDocument;
    BtnText: TButton;
    Memo2: TMemo;
    BtnConverter: TButton;
    EdtXml: TLabeledEdit;
    procedure BtnTextClick(Sender: TObject);
    procedure BtnConverterClick(Sender: TObject);
  private

    { Private declarations }
  public
    function RemoverTag(tag: string; valor: string): string;
    { Public declarations }

  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.BtnConverterClick(Sender: TObject);
var
 i:integer;
// Posicao: integer;
 m: string;
begin
  Memo2.Lines.Clear;
  for i := 0 to Pred(Memo1.Lines.Count) do
  begin
//    if (Memo1.Lines.Strings[i].Contains('<ide>') = True) then Memo2.Lines.Add(memo1.Lines.Strings[i]);
    if (Memo1.Lines.Strings[i].Contains('<infCte ') = True) then Memo2.Lines.Add('incluirCTe');
    if (Memo1.Lines.Strings[i].Contains('versao=') = True) then Memo2.Lines.Add('versao_2=3.00');
    if (Memo1.Lines.Strings[i].Contains('<cUF>') = True) then Memo2.Lines.Add('cUF_5='+RemoverTag('cUF',memo1.Lines.Strings[i]));

    if (Memo1.Lines.Strings[i].Contains('<cCT>') = True) then Memo2.Lines.Add('cCT_6='+RemoverTag('cCT',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CFOP>') = True) then Memo2.Lines.Add('CFOP_7='+RemoverTag('CFOP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<natOp>') = True) then Memo2.Lines.Add('natOp_8='+RemoverTag('natOp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<mod>') = True) then Memo2.Lines.Add('mod_10='+RemoverTag('mod',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<serie>') = True) then Memo2.Lines.Add('serie_11='+RemoverTag('serie',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nCT>') = True) then Memo2.Lines.Add('nCT_12='+RemoverTag('nCT',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dhEmi>') = True) then Memo2.Lines.Add('dhEmi_13='+RemoverTag('dhEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpImp>') = True) then Memo2.Lines.Add('tpImp_14='+RemoverTag('tpImp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpEmis>') = True) then Memo2.Lines.Add('tpEmis_15='+RemoverTag('tpEmis',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cDV>') = True) then Memo2.Lines.Add('cDV_16='+RemoverTag('cDV',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpAmb>') = True) then Memo2.Lines.Add('tpAmb_17='+RemoverTag('tpAmb',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpCTe>') = True) then Memo2.Lines.Add('tpCTe_18='+RemoverTag('tpCTe',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<procEmi>') = True) then Memo2.Lines.Add('procEmi_19='+RemoverTag('tpprocEmiAmb',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<verProc>') = True) then Memo2.Lines.Add('verProc_20='+RemoverTag('verProc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMunEnv>') = True) then Memo2.Lines.Add('cMunEnv_672='+RemoverTag('cMunEnv',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMunEnv>') = True) then Memo2.Lines.Add('xMunEnv_673='+RemoverTag('xMunEnv',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UFEnv>') = True) then Memo2.Lines.Add('UFEnv_674='+RemoverTag('UFEnv',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<modal>') = True) then Memo2.Lines.Add('tmodal_25='+RemoverTag('modal',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpServ>') = True) then Memo2.Lines.Add('tpServ_26='+RemoverTag('tpServ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMunIni>') = True) then Memo2.Lines.Add('cMunIni_27='+RemoverTag('cMunIni',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMunIni>') = True) then Memo2.Lines.Add('xMunIni_28='+RemoverTag('xMunIni',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UFIni>') = True) then Memo2.Lines.Add('UFIni_29='+RemoverTag('UFIni',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMunFim>') = True) then Memo2.Lines.Add('cMunFim_30='+RemoverTag('cMunFim',memo1.Lines.Strings[i]));


    if (Memo1.Lines.Strings[i].Contains('<xMunFim>') = True) then Memo2.Lines.Add('xMunFim_31='+RemoverTag('xMunFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UFFim>') = True) then Memo2.Lines.Add('UFFim_32='+RemoverTag('UFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<retira>') = True) then Memo2.Lines.Add('retira_33='+RemoverTag('retira',memo1.Lines.Strings[i]));

   if (Memo1.Lines.Strings[i].Contains('<retira>') = True) then Memo2.Lines.Add('retira_33='+RemoverTag('retira',memo1.Lines.Strings[i]));
//   if (Memo1.Lines.Strings[i].Contains('<xDetRetira>') = True) then Memo2.Lines.Add('xDetRetira_34='+RemoverTag('xDetRetira',memo1.Lines.Strings[i]));

    if (Memo1.Lines.Strings[i].Contains('<indIEToma>') = True) then Memo2.Lines.Add('toma_36=0');
    if (Memo1.Lines.Strings[i].Contains('<indIEToma>') = True) then Memo2.Lines.Add('toma_38=');


    if (Memo1.Lines.Strings[i].Contains('</ide>') = True) then Memo2.Lines.Add('</ide>');
    if (Memo1.Lines.Strings[i].Contains('<compl>') = True) then Memo2.Lines.Add('<compl>');
    if (Memo1.Lines.Strings[i].Contains('<xObs>') = True) then Memo2.Lines.Add('xObs_87='+RemoverTag('xObs',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ObsCont ') = True) then Memo2.Lines.Add('<ObsCont xCampo="LEI_TRANSP">');
    if (Memo1.Lines.Strings[i].Contains('<xTexto>') = True) then Memo2.Lines.Add('xObs_90='+RemoverTag('xTexto',memo1.Lines.Strings[i]));
{
    if (Memo1.Lines.Strings[i].Contains('<xTexto>') = True) then Memo2.Lines.Add('xTexto='+RemoverTag('modxTexto',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ObsFisco>') = True) then Memo2.Lines.Add('ObsFisco='+RemoverTag('modObsFisco',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCampo>') = True) then Memo2.Lines.Add('xCampo='+RemoverTag('modxCampo',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xTexto>') = True) then Memo2.Lines.Add('xTexto='+RemoverTag('modxTexto',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<emit>') = True) then Memo2.Lines.Add('emit='+RemoverTag('modemit',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ_95='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE_96='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome_97='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xFant>') = True) then Memo2.Lines.Add('xFant_98='+RemoverTag('modxFant',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<enderEmit>') = True) then Memo2.Lines.Add('enderEmit='+RemoverTag('modenderEmit',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr_100='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro_101='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl_102='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro_103='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun_104='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun_105='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CEP>') = True) then Memo2.Lines.Add('CEP_106='+RemoverTag('modCEP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF_107='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fone>') = True) then Memo2.Lines.Add('fone_110='+RemoverTag('modfone',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<rem>') = True) then Memo2.Lines.Add('rem='+RemoverTag('modrem',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ_112='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF_113='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE_114='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome_115='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xFant>') = True) then Memo2.Lines.Add('xFant_116='+RemoverTag('modxFant',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fone>') = True) then Memo2.Lines.Add('fone_117='+RemoverTag('modfone',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<enderReme>') = True) then Memo2.Lines.Add('enderReme='+RemoverTag('modenderReme',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr_119='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro_120='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl_121='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro_122='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun_123='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun_124='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CEP>') = True) then Memo2.Lines.Add('CEP_125='+RemoverTag('modCEP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF_126='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cPais>') = True) then Memo2.Lines.Add('cPais_127='+RemoverTag('modcPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xPais>') = True) then Memo2.Lines.Add('xPais_128='+RemoverTag('modxPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<email>') = True) then Memo2.Lines.Add('email_604='+RemoverTag('modemail',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<locColeta>') = True) then Memo2.Lines.Add('locColeta='+RemoverTag('modlocColeta',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ_165='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF_166='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome_168='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr_171='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro_172='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl_173='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro_174='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun_175='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun_176='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF_178='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<exped>') = True) then Memo2.Lines.Add('exped='+RemoverTag('modexped',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ_182='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF_183='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE_184='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fone>') = True) then Memo2.Lines.Add('fone_186='+RemoverTag('modfone',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<enderExped>') = True) then Memo2.Lines.Add('enderExped='+RemoverTag('modenderExped',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr_188='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro_189='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl_190='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro_191='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun_192='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun_193='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CEP>') = True) then Memo2.Lines.Add('CEP_194='+RemoverTag('modCEP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF_195='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cPais>') = True) then Memo2.Lines.Add('cPais_196='+RemoverTag('modcPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xPais>') = True) then Memo2.Lines.Add('xPais_197='+RemoverTag('modxPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<email>') = True) then Memo2.Lines.Add('email_607='+RemoverTag('modemail',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<receb>') = True) then Memo2.Lines.Add('receb='+RemoverTag('modreceb',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ_199='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF_200='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE_201='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome_202='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fone>') = True) then Memo2.Lines.Add('fone_203='+RemoverTag('modfone',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<enderReceb>') = True) then Memo2.Lines.Add('enderReceb='+RemoverTag('modenderReceb',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr_206='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro_207='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl_208='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro_209='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun_210='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun_211='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CEP>') = True) then Memo2.Lines.Add('CEP_212='+RemoverTag('modCEP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF_213='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cPais>') = True) then Memo2.Lines.Add('cPais_214='+RemoverTag('modcPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xPais>') = True) then Memo2.Lines.Add('xPais_215='+RemoverTag('modxPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<email>') = True) then Memo2.Lines.Add('email_608='+RemoverTag('modemail',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dest>') = True) then Memo2.Lines.Add('dest='+RemoverTag('moddest',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fone>') = True) then Memo2.Lines.Add('fone='+RemoverTag('modfone',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ISUF>') = True) then Memo2.Lines.Add('ISUF='+RemoverTag('modISUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<enderDest>') = True) then Memo2.Lines.Add('enderDest='+RemoverTag('modenderDest',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CEP>') = True) then Memo2.Lines.Add('CEP='+RemoverTag('modCEP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cPais>') = True) then Memo2.Lines.Add('cPais='+RemoverTag('modcPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xPais>') = True) then Memo2.Lines.Add('xPais='+RemoverTag('modxPais',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<email>') = True) then Memo2.Lines.Add('email='+RemoverTag('modemail',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<locEnt>') = True) then Memo2.Lines.Add('locEnt='+RemoverTag('modlocEnt',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vPrest>') = True) then Memo2.Lines.Add('vPrest='+RemoverTag('modvPrest',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vTPrest>') = True) then Memo2.Lines.Add('vTPrest_228='+RemoverTag('modvTPrest',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vRec>') = True) then Memo2.Lines.Add('vRec_229='+RemoverTag('modvRec',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<Comp>') = True) then Memo2.Lines.Add('Comp='+RemoverTag('modComp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vComp>') = True) then Memo2.Lines.Add('vComp='+RemoverTag('modvComp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<imp>') = True) then Memo2.Lines.Add('imp='+RemoverTag('modimp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMS>') = True) then Memo2.Lines.Add('ICMS='+RemoverTag('modICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMS00>') = True) then Memo2.Lines.Add('ICMS00='+RemoverTag('modICMS00',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CST>') = True) then Memo2.Lines.Add('CST_609='+RemoverTag('modCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBC>') = True) then Memo2.Lines.Add('vBC_610='+RemoverTag('modvBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMS>') = True) then Memo2.Lines.Add('pICMS_611='+RemoverTag('modpICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMS>') = True) then Memo2.Lines.Add('vICMS_612='+RemoverTag('modvICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMS20>') = True) then Memo2.Lines.Add('ICMS20='+RemoverTag('modICMS20',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CST>') = True) then Memo2.Lines.Add('CST_613='+RemoverTag('modCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pRedBC>') = True) then Memo2.Lines.Add('pRedBC_614='+RemoverTag('modpRedBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBC>') = True) then Memo2.Lines.Add('vBC_615='+RemoverTag('modvBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMS>') = True) then Memo2.Lines.Add('pICMS_616='+RemoverTag('modpICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMS>') = True) then Memo2.Lines.Add('vICMS_617='+RemoverTag('modvICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMS45>') = True) then Memo2.Lines.Add('ICMS45='+RemoverTag('modICMS45',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CST>') = True) then Memo2.Lines.Add('CST_618='+RemoverTag('modCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMS60>') = True) then Memo2.Lines.Add('ICMS60='+RemoverTag('modICMS60',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CST>') = True) then Memo2.Lines.Add('CST_619='+RemoverTag('modCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBCSTRet>') = True) then Memo2.Lines.Add('vBCSTRet_620='+RemoverTag('modvBCSTRet',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMSSTRet>') = True) then Memo2.Lines.Add('vICMSSTRet_621='+RemoverTag('modvICMSSTRet',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMSSTRet>') = True) then Memo2.Lines.Add('pICMSSTRet_622='+RemoverTag('modpICMSSTRet',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vCred>') = True) then Memo2.Lines.Add('vCred_623='+RemoverTag('modvCred',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMS90>') = True) then Memo2.Lines.Add('ICMS90='+RemoverTag('modICMS90',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CST>') = True) then Memo2.Lines.Add('CST_624='+RemoverTag('modCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pRedBC>') = True) then Memo2.Lines.Add('pRedBC_625='+RemoverTag('modpRedBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBC>') = True) then Memo2.Lines.Add('vBC_626='+RemoverTag('modvBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMS>') = True) then Memo2.Lines.Add('pICMS_627='+RemoverTag('modpICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMS>') = True) then Memo2.Lines.Add('VICMS_628='+RemoverTag('modvICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vCred>') = True) then Memo2.Lines.Add('vCred_629='+RemoverTag('modvCred',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UCMSOutraUF>') = True) then Memo2.Lines.Add('ICMSOutraUF='+RemoverTag('modUCMSOutraUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CST>') = True) then Memo2.Lines.Add('CST_630='+RemoverTag('modCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pRedBCOutraUF>') = True) then Memo2.Lines.Add('pRedBCOutraUF_631='+RemoverTag('modpRedBCOutraUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBCOutraUF>') = True) then Memo2.Lines.Add('vBCOutraUF_632='+RemoverTag('modvBCOutraUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMSOutraUF>') = True) then Memo2.Lines.Add('pICMSOutraUF_633='+RemoverTag('modpICMSOutraUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMSOutraUF>') = True) then Memo2.Lines.Add('vICMSOutraUF_634='+RemoverTag('modvICMSOutraUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMSSN>') = True) then Memo2.Lines.Add('ICMSSN='+RemoverTag('modICMSSN',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cst>') = True) then Memo2.Lines.Add('CST='+RemoverTag('modcst',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<indSN>') = True) then Memo2.Lines.Add('indSN_635='+RemoverTag('modindSN',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ICMSUFFim>') = True) then Memo2.Lines.Add('ICMSUFFim='+RemoverTag('modICMSUFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBCUFFim>') = True) then Memo2.Lines.Add('vBCUFFim_676='+RemoverTag('modvBCUFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pFCPUFFim>') = True) then Memo2.Lines.Add('pFCPUFFim_682='+RemoverTag('modpFCPUFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMSUFFim>') = True) then Memo2.Lines.Add('pICMSUFFim_677='+RemoverTag('modpICMSUFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pICMSInter>') = True) then Memo2.Lines.Add('pICMSInter_678='+RemoverTag('modpICMSInter',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vFCPUFFim>') = True) then Memo2.Lines.Add('vFCPUFFim_683='+RemoverTag('modvFCPUFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMSUFFim>') = True) then Memo2.Lines.Add('vICMSUFFim_680='+RemoverTag('modvICMSUFFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMSUFIni>') = True) then Memo2.Lines.Add('vICMSUFIni_681='+RemoverTag('modvICMSUFIni',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vTotTrib>') = True) then Memo2.Lines.Add('vTotTrib_268='+RemoverTag('modvTotTrib',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infAdFisco>') = True) then Memo2.Lines.Add('infAdFisco_267='+RemoverTag('modinfAdFisco',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCTeNorm>') = True) then Memo2.Lines.Add('infCTeNorm='+RemoverTag('modinfCTeNorm',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCarga>') = True) then Memo2.Lines.Add('infCarga='+RemoverTag('modinfCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vCarga>') = True) then Memo2.Lines.Add('vCarga_671='+RemoverTag('modvCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<proPred>') = True) then Memo2.Lines.Add('proPred_271='+RemoverTag('modproPred',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xOutCat>') = True) then Memo2.Lines.Add('xOutCat_272='+RemoverTag('modxOutCat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infQ>') = True) then Memo2.Lines.Add('infQ='+RemoverTag('modinfQ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cUnid>') = True) then Memo2.Lines.Add('cUnid_274='+RemoverTag('modcUnid',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpMed>') = True) then Memo2.Lines.Add('tpMed_275='+RemoverTag('modtpMed',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qCarga>') = True) then Memo2.Lines.Add('qCarga_276='+RemoverTag('modqCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infDoc>') = True) then Memo2.Lines.Add('infDoc='+RemoverTag('modinfDoc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infNF>') = True) then Memo2.Lines.Add('infNF='+RemoverTag('modinfNF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nRoma>') = True) then Memo2.Lines.Add('nRoma_130='+RemoverTag('modnRoma',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nPed>') = True) then Memo2.Lines.Add('nPed_131='+RemoverTag('modnPed',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<mod>') = True) then Memo2.Lines.Add('mod_605='+RemoverTag('modmod',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<serie>') = True) then Memo2.Lines.Add('serie_132='+RemoverTag('modserie',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nDoc>') = True) then Memo2.Lines.Add('nDoc_133='+RemoverTag('modnDoc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dEmi>') = True) then Memo2.Lines.Add('dEmi_134='+RemoverTag('moddEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBC>') = True) then Memo2.Lines.Add('vBC_135='+RemoverTag('modvBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vICMS>') = True) then Memo2.Lines.Add('vICMS_136='+RemoverTag('modvICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vBCST>') = True) then Memo2.Lines.Add('vBCST_137='+RemoverTag('modvBCST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vST>') = True) then Memo2.Lines.Add('vST_138='+RemoverTag('modvST',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vProd>') = True) then Memo2.Lines.Add('vProd_139='+RemoverTag('modvProd',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vNF>') = True) then Memo2.Lines.Add('vNF_140='+RemoverTag('modvNF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nCFOP>') = True) then Memo2.Lines.Add('nCFOP_141='+RemoverTag('modnCFOP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vPeso>') = True) then Memo2.Lines.Add('vPeso='+RemoverTag('modvPeso',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidTransp>') = True) then Memo2.Lines.Add('infUnidTransp='+RemoverTag('modinfUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidTranssp>') = True) then Memo2.Lines.Add('tpUnidTransp='+RemoverTag('modtpUnidTranssp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidTransp>') = True) then Memo2.Lines.Add('idUnidTransp='+RemoverTag('modidUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidTransp>') = True) then Memo2.Lines.Add('lacUnidTransp='+RemoverTag('modlacUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidCarga>') = True) then Memo2.Lines.Add('infUnidCarga='+RemoverTag('modinfUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidCarga>') = True) then Memo2.Lines.Add('tpUnidCarga='+RemoverTag('modtpUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidCarga>') = True) then Memo2.Lines.Add('idUnidCarga='+RemoverTag('modidUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidCarga>') = True) then Memo2.Lines.Add('lacUnidCarga='+RemoverTag('modlacUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidCarga>') = True) then Memo2.Lines.Add('infUnidCarga='+RemoverTag('modinfUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidCarga>') = True) then Memo2.Lines.Add('tpUnidCarga='+RemoverTag('modtpUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidCarga>') = True) then Memo2.Lines.Add('idUnidCarga='+RemoverTag('modidUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidCarga>') = True) then Memo2.Lines.Add('lacUnidCarga='+RemoverTag('modlacUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infNFe>') = True) then Memo2.Lines.Add('infNFe='+RemoverTag('modinfNFe',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chave>') = True) then Memo2.Lines.Add('chave='+RemoverTag('modchave',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<PIN>') = True) then Memo2.Lines.Add('PIN='+RemoverTag('modPIN',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dPrev>') = True) then Memo2.Lines.Add('dPrev='+RemoverTag('moddPrev',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidTransp>') = True) then Memo2.Lines.Add('infUnidTransp='+RemoverTag('modinfUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidTransp>') = True) then Memo2.Lines.Add('tpUnidTransp='+RemoverTag('modtpUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidTransp>') = True) then Memo2.Lines.Add('idUnidTransp='+RemoverTag('modidUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidTransp>') = True) then Memo2.Lines.Add('lacUnidTransp='+RemoverTag('modlacUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidCarga>') = True) then Memo2.Lines.Add('infUnidCarga='+RemoverTag('modinfUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidCarga>') = True) then Memo2.Lines.Add('tpUnidCarga='+RemoverTag('modtpUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidCarga>') = True) then Memo2.Lines.Add('idUnidCarga='+RemoverTag('modidUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidCarga>') = True) then Memo2.Lines.Add('lacUnidCarga='+RemoverTag('modlacUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidCarga>') = True) then Memo2.Lines.Add('infUnidCarga='+RemoverTag('modinfUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidCarga>') = True) then Memo2.Lines.Add('tpUnidCarga='+RemoverTag('modtpUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidCarga>') = True) then Memo2.Lines.Add('idUnidCarga='+RemoverTag('modidUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidCarga>') = True) then Memo2.Lines.Add('lacUnidCarga='+RemoverTag('modlacUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infOutros>') = True) then Memo2.Lines.Add('infOutros='+RemoverTag('modinfOutros',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpDoc>') = True) then Memo2.Lines.Add('tpDoc='+RemoverTag('modtpDoc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<descOutros>') = True) then Memo2.Lines.Add('descOutros='+RemoverTag('moddescOutros',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nDoc>') = True) then Memo2.Lines.Add('nDoc='+RemoverTag('modnDoc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dEmi>') = True) then Memo2.Lines.Add('dEmi='+RemoverTag('moddEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vDocFisc>') = True) then Memo2.Lines.Add('vDocFisc='+RemoverTag('modvDocFisc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dPrev>') = True) then Memo2.Lines.Add('dPrev='+RemoverTag('moddPrev',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidTtransp>') = True) then Memo2.Lines.Add('infUnidTransp='+RemoverTag('modinfUnidTtransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidTransp>') = True) then Memo2.Lines.Add('tpUnidTransp='+RemoverTag('modtpUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidTransp>') = True) then Memo2.Lines.Add('idUnidTransp='+RemoverTag('modidUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidTransp>') = True) then Memo2.Lines.Add('lacUnidTransp='+RemoverTag('modlacUnidTransp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidCarga>') = True) then Memo2.Lines.Add('infUnidCarga='+RemoverTag('modinfUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidCarga>') = True) then Memo2.Lines.Add('tpUnidCarga='+RemoverTag('modtpUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidCarga>') = True) then Memo2.Lines.Add('idUnidCarga='+RemoverTag('modidUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidCarga>') = True) then Memo2.Lines.Add('lacUnidCarga='+RemoverTag('modlacUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infUnidCarga>') = True) then Memo2.Lines.Add('infUnidCarga='+RemoverTag('modinfUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidCarga>') = True) then Memo2.Lines.Add('tpUnidCarga='+RemoverTag('modtpUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idUnidCarga>') = True) then Memo2.Lines.Add('idUnidCarga='+RemoverTag('modidUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<lacUnidCarga>') = True) then Memo2.Lines.Add('lacUnidCarga='+RemoverTag('modlacUnidCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nLacre>') = True) then Memo2.Lines.Add('nLacre='+RemoverTag('modnLacre',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qtdRat>') = True) then Memo2.Lines.Add('qtdRat='+RemoverTag('modqtdRat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<docAnt>') = True) then Memo2.Lines.Add('docAnt='+RemoverTag('moddocAnt',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<emiDocAnt>') = True) then Memo2.Lines.Add('emiDocAnt='+RemoverTag('modemiDocAnt',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idDocAnt>') = True) then Memo2.Lines.Add('idDocAnt='+RemoverTag('modidDocAnt',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idDocAntPap>') = True) then Memo2.Lines.Add('idDocAntPap='+RemoverTag('modidDocAntPap',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpDoc>') = True) then Memo2.Lines.Add('tpDoc='+RemoverTag('modtpDoc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<serie>') = True) then Memo2.Lines.Add('serie='+RemoverTag('modserie',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<subser>') = True) then Memo2.Lines.Add('subser='+RemoverTag('modsubser',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nDoc>') = True) then Memo2.Lines.Add('nDoc='+RemoverTag('modnDoc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dEmi>') = True) then Memo2.Lines.Add('dEmi='+RemoverTag('moddEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idDocAntEle>') = True) then Memo2.Lines.Add('idDocAntEle='+RemoverTag('modidDocAntEle',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chave>') = True) then Memo2.Lines.Add('chCTe='+RemoverTag('modchave',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<respSeg>') = True) then Memo2.Lines.Add('respSeg='+RemoverTag('modrespSeg',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xSeg>') = True) then Memo2.Lines.Add('xSeg='+RemoverTag('modxSeg',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nApol>') = True) then Memo2.Lines.Add('nApol='+RemoverTag('modnApol',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nAver>') = True) then Memo2.Lines.Add('nAver='+RemoverTag('modnAver',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vCarga>') = True) then Memo2.Lines.Add('vCarga='+RemoverTag('modvCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infModal>') = True) then Memo2.Lines.Add('infModal='+RemoverTag('modinfModal',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<versaoModal>') = True) then Memo2.Lines.Add('versaoModal='+RemoverTag('modversaoModal',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<rodo>') = True) then Memo2.Lines.Add('rodo='+RemoverTag('modrodo',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<RNTRC>') = True) then Memo2.Lines.Add('RNTRC='+RemoverTag('modRNTRC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<occ>') = True) then Memo2.Lines.Add('occ='+RemoverTag('modocc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<serie>') = True) then Memo2.Lines.Add('serie='+RemoverTag('modserie',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nOcc>') = True) then Memo2.Lines.Add('nOcc='+RemoverTag('modnOcc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dEmi>') = True) then Memo2.Lines.Add('dEmi='+RemoverTag('moddEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<emiOcc>') = True) then Memo2.Lines.Add('emiOcc='+RemoverTag('modemiOcc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cInt>') = True) then Memo2.Lines.Add('cInt='+RemoverTag('modcInt',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fone>') = True) then Memo2.Lines.Add('fone='+RemoverTag('modfone',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<aereo>') = True) then Memo2.Lines.Add('aereo='+RemoverTag('modaereo',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nMinu>') = True) then Memo2.Lines.Add('nMinu='+RemoverTag('modnMinu',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nOCA>') = True) then Memo2.Lines.Add('nOCA='+RemoverTag('modnOCA',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dPrevAereo>') = True) then Memo2.Lines.Add('dPrevAereo='+RemoverTag('moddPrevAereo',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLagEmi>') = True) then Memo2.Lines.Add('xLAgEmi='+RemoverTag('modxLagEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IdT>') = True) then Memo2.Lines.Add('IdT='+RemoverTag('modIdT',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tarifa>') = True) then Memo2.Lines.Add('tarifa='+RemoverTag('modtarifa',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CL>') = True) then Memo2.Lines.Add('CL='+RemoverTag('modCL',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cTar>') = True) then Memo2.Lines.Add('cTar='+RemoverTag('modcTar',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vTar>') = True) then Memo2.Lines.Add('vTar='+RemoverTag('modvTar',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<natCarga>') = True) then Memo2.Lines.Add('natCarga='+RemoverTag('modnatCarga',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xDime>') = True) then Memo2.Lines.Add('xDime='+RemoverTag('modxDime',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cInfManu>') = True) then Memo2.Lines.Add('cInfManu='+RemoverTag('modcInfManu',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cIMP>') = True) then Memo2.Lines.Add('cIMP='+RemoverTag('modcIMP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<aquav>') = True) then Memo2.Lines.Add('aquav='+RemoverTag('modaquav',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vPrest>') = True) then Memo2.Lines.Add('vPrest='+RemoverTag('modvPrest',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vAFRMM>') = True) then Memo2.Lines.Add('vAFRMM='+RemoverTag('modvAFRMM',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nCtrl>') = True) then Memo2.Lines.Add('nCtrl='+RemoverTag('modnCtrl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNavio>') = True) then Memo2.Lines.Add('xNavio='+RemoverTag('modxNavio',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<balsa>') = True) then Memo2.Lines.Add('balsa='+RemoverTag('modbalsa',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBalsa>') = True) then Memo2.Lines.Add('xBalsa='+RemoverTag('modxBalsa',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nViag>') = True) then Memo2.Lines.Add('nViag='+RemoverTag('modnViag',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<direc>') = True) then Memo2.Lines.Add('direc='+RemoverTag('moddirec',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpNav>') = True) then Memo2.Lines.Add('irin='+RemoverTag('modtpNav',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<irin>') = True) then Memo2.Lines.Add('tpNav='+RemoverTag('modirin',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ferrov>') = True) then Memo2.Lines.Add('ferrov='+RemoverTag('modferrov',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpTraf>') = True) then Memo2.Lines.Add('tpTraf='+RemoverTag('modtpTraf',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<trafMut>') = True) then Memo2.Lines.Add('trafMut='+RemoverTag('modtrafMut',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<respFat>') = True) then Memo2.Lines.Add('respFat='+RemoverTag('modrespFat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<terrEmi>') = True) then Memo2.Lines.Add('terrEmi='+RemoverTag('modterrEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fluxo>') = True) then Memo2.Lines.Add('fluxo='+RemoverTag('modfluxo',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<idTrem>') = True) then Memo2.Lines.Add('idTrem='+RemoverTag('modidTrem',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vFrete>') = True) then Memo2.Lines.Add('vFrete='+RemoverTag('modvFrete',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<ferroEnv>') = True) then Memo2.Lines.Add('ferroEnv='+RemoverTag('modferroEnv',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cInt>') = True) then Memo2.Lines.Add('cInt='+RemoverTag('modcInt',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<IE>') = True) then Memo2.Lines.Add('IE='+RemoverTag('modIE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNome>') = True) then Memo2.Lines.Add('xNome='+RemoverTag('modxNome',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<enderFerro>') = True) then Memo2.Lines.Add('enderFerro='+RemoverTag('modenderFerro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xLgr>') = True) then Memo2.Lines.Add('xLgr='+RemoverTag('modxLgr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCpl>') = True) then Memo2.Lines.Add('xCpl='+RemoverTag('modxCpl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xBairro>') = True) then Memo2.Lines.Add('xBairro='+RemoverTag('modxBairro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMun>') = True) then Memo2.Lines.Add('cMun='+RemoverTag('modcMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xMun>') = True) then Memo2.Lines.Add('xMun='+RemoverTag('modxMun',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CEP>') = True) then Memo2.Lines.Add('CEP='+RemoverTag('modCEP',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<UF>') = True) then Memo2.Lines.Add('UF='+RemoverTag('modUF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<detVag>') = True) then Memo2.Lines.Add('detVag='+RemoverTag('moddetVag',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nVag>') = True) then Memo2.Lines.Add('nVag='+RemoverTag('modnVag',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cap>') = True) then Memo2.Lines.Add('cap='+RemoverTag('modcap',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpVag>') = True) then Memo2.Lines.Add('tpVag='+RemoverTag('modtpVag',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pesoR>') = True) then Memo2.Lines.Add('pesoR='+RemoverTag('modpesoR',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pesoBC>') = True) then Memo2.Lines.Add('pesoBC='+RemoverTag('modpesoBC',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<duto>') = True) then Memo2.Lines.Add('duto='+RemoverTag('modduto',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vTar>') = True) then Memo2.Lines.Add('vTar='+RemoverTag('modvTar',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dIni>') = True) then Memo2.Lines.Add('dIni='+RemoverTag('moddIni',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dFim>') = True) then Memo2.Lines.Add('dFim='+RemoverTag('moddFim',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<multimodal>') = True) then Memo2.Lines.Add('multimodal='+RemoverTag('modmultimodal',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<COTM>') = True) then Memo2.Lines.Add('COTM='+RemoverTag('modCOTM',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<indNegociavel>') = True) then Memo2.Lines.Add('indNegociavel='+RemoverTag('modindNegociavel',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<peri>') = True) then Memo2.Lines.Add('peri='+RemoverTag('modperi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nONU>') = True) then Memo2.Lines.Add('nONU='+RemoverTag('modnONU',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xNomeAE>') = True) then Memo2.Lines.Add('xNomeAE='+RemoverTag('modxNomeAE',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xClaRisco>') = True) then Memo2.Lines.Add('xClaRisco='+RemoverTag('modxClaRisco',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<grEmb>') = True) then Memo2.Lines.Add('grEmb='+RemoverTag('modgrEmb',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qTotProd>') = True) then Memo2.Lines.Add('qTotProd='+RemoverTag('modqTotProd',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qVolTipo>') = True) then Memo2.Lines.Add('qVolTipo='+RemoverTag('modqVolTipo',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<pontoFulgor>') = True) then Memo2.Lines.Add('pontoFulgor='+RemoverTag('modpontoFulgor',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<veicNovos>') = True) then Memo2.Lines.Add('veicNovos='+RemoverTag('modveicNovos',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chassi>') = True) then Memo2.Lines.Add('chassi='+RemoverTag('modchassi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cCor>') = True) then Memo2.Lines.Add('cCor='+RemoverTag('modcCor',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xCor>') = True) then Memo2.Lines.Add('xCor='+RemoverTag('modxCor',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cMod>') = True) then Memo2.Lines.Add('cMod='+RemoverTag('modcMod',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vUnit>') = True) then Memo2.Lines.Add('vUnit='+RemoverTag('modvUnit',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vFrete>') = True) then Memo2.Lines.Add('vFrete='+RemoverTag('modvFrete',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<cobr>') = True) then Memo2.Lines.Add('cobr='+RemoverTag('modcobr',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<fat>') = True) then Memo2.Lines.Add('fat='+RemoverTag('modfat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nFat>') = True) then Memo2.Lines.Add('nFat='+RemoverTag('modnFat',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vOrig>') = True) then Memo2.Lines.Add('vOrig='+RemoverTag('modvOrig',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vDesc>') = True) then Memo2.Lines.Add('vDesc='+RemoverTag('modvDesc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vLiq>') = True) then Memo2.Lines.Add('vLiq='+RemoverTag('modvLiq',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dup>') = True) then Memo2.Lines.Add('dup='+RemoverTag('moddup',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nDup>') = True) then Memo2.Lines.Add('nDup='+RemoverTag('modnDup',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dVenc>') = True) then Memo2.Lines.Add('dVenc='+RemoverTag('moddVenc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<vDuq>') = True) then Memo2.Lines.Add('vDuq='+RemoverTag('modvDuq',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCteSub>') = True) then Memo2.Lines.Add('infCteSub='+RemoverTag('modinfCteSub',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chCte>') = True) then Memo2.Lines.Add('chCte='+RemoverTag('modchCte',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tomaICMS>') = True) then Memo2.Lines.Add('tomaICMS='+RemoverTag('modtomaICMS',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<refNFe>') = True) then Memo2.Lines.Add('refNFe='+RemoverTag('modrefNFe',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<refNF>') = True) then Memo2.Lines.Add('refNF='+RemoverTag('modrefNF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<mod>') = True) then Memo2.Lines.Add('mod='+RemoverTag('modmod',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<serie>') = True) then Memo2.Lines.Add('serie='+RemoverTag('modserie',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<subserie>') = True) then Memo2.Lines.Add('subserie='+RemoverTag('modsubserie',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<nro>') = True) then Memo2.Lines.Add('nro='+RemoverTag('modnro',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<valor>') = True) then Memo2.Lines.Add('valor='+RemoverTag('modvalor',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dEmi>') = True) then Memo2.Lines.Add('dEmi='+RemoverTag('moddEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<refCte>') = True) then Memo2.Lines.Add('refCte='+RemoverTag('modrefCte',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<refCteAnu>') = True) then Memo2.Lines.Add('refCteAnu='+RemoverTag('modrefCteAnu',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<indAlteraToma>') = True) then Memo2.Lines.Add('indAlteraToma='+RemoverTag('modindAlteraToma',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCteComp>') = True) then Memo2.Lines.Add('infCteComp='+RemoverTag('modinfCteComp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chCTe>') = True) then Memo2.Lines.Add('chCTe='+RemoverTag('modchCTe',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCteAnu>') = True) then Memo2.Lines.Add('infCteAnu='+RemoverTag('modinfCteAnu',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chCte>') = True) then Memo2.Lines.Add('chCte='+RemoverTag('modchCte',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dEmi>') = True) then Memo2.Lines.Add('dEmi='+RemoverTag('moddEmi',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<autXML>') = True) then Memo2.Lines.Add('autXML='+RemoverTag('modautXML',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CNPJ>') = True) then Memo2.Lines.Add('CNPJ='+RemoverTag('modCNPJ',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<CPF>') = True) then Memo2.Lines.Add('CPF='+RemoverTag('modCPF',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dadosAdic>') = True) then Memo2.Lines.Add('dadosAdic='+RemoverTag('moddadosAdic',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<B2B>') = True) then Memo2.Lines.Add('B2B='+RemoverTag('modB2B',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<type>') = True) then Memo2.Lines.Add('type='+RemoverTag('modtype',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<PIN>') = True) then Memo2.Lines.Add('PIN='+RemoverTag('modPIN',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<tpUnidTranssp>') = True) then Memo2.Lines.Add('tpUnidTranssp='+RemoverTag('modtpUnidTranssp',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<dPrev>') = True) then Memo2.Lines.Add('dPrev='+RemoverTag('moddPrev',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infGlobalizado>') = True) then Memo2.Lines.Add('infGlobalizado='+RemoverTag('modinfGlobalizado',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<xObs>') = True) then Memo2.Lines.Add('xObs_1413='+RemoverTag('modxObs',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infServVinc>') = True) then Memo2.Lines.Add('infServVinc='+RemoverTag('modinfServVinc',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCTeMultimodal>') = True) then Memo2.Lines.Add('infCTeMultimodal='+RemoverTag('modinfCTeMultimodal',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<chCTeMultimodal>') = True) then Memo2.Lines.Add('ChCTeMultimodal_1415='+RemoverTag('modchCTeMultimodal',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<infCTeSupl>') = True) then Memo2.Lines.Add('infCTeSupl='+RemoverTag('modinfCTeSupl',memo1.Lines.Strings[i]));
    if (Memo1.Lines.Strings[i].Contains('<qrCodCTe>') = True) then Memo2.Lines.Add('qrCodCTe='+RemoverTag('modqrCodCTe',memo1.Lines.Strings[i]));

                           }

  end;
end;


procedure TForm1.BtnTextClick(Sender: TObject);
begin
Memo1.Lines.Clear;

//   memo1.Lines.LoadFromFile('C:\XMLs\Exemplo_CTE.xml');
   memo1.Lines.LoadFromFile(EdtXml.Text);

end;


function TForm1.RemoverTag(tag, valor: string): string;
var
 x : string;
begin
  Result := '';
  x:= StringReplace(valor,'<'+tag+'>',' ',[]);
  x:= StringReplace(x,'</'+tag+'>',' ',[]);
  Result := Trim(x);
end;


end.
